blueprint:
  name: Control of Novy hoods
  description: >
     With this you can control a Novy hood through a numeric input.
     Requirements: RFXTRX integration, a Numeric Input Helper with a range of 0 - 4 and step size of 1. 0 is off, 1-3 are regular speeds, 4 is boost.
  domain: automation
  source_url: https://github.com/steveddt/homeassistant/novy.yaml
  input:
    speed_input:
      name: Numeric Input for speed
      description: "Numeric input used to set the speed."
      selector:
        entity:
    command_on:
      name: Command On
      description: "Command to activate"
      selector:
        text:
      default: "08170B090000000100"
	command_off:
      name: Command Off
      description: "Command to disactivate"
      selector:
        text:
      default: "08170B000000000100"  
	command_up:
      name: Command Up
      description: "Command to send to increase speed"
      selector:
        text:
      default: "08170B0C0000000200"
    command_down:
      name: Command Down
      description: "Command to send to reduce speed"
      selector:
        text:
      default: "08170B0D0000000300"
	command_light:
      name: Command Light
      description: "Command to toggle the light"
      selector:
        text:
      default: "08170B010000020400"
    timer_boost:
      name: Boost Timer
      description: "Timer for boost function, set shorter than internal hood timer"
      default: 5
      selector:
        number:
          min: 1
          max: 6
          unit_of_measurement: minutes
    timer_off:
      name: Off Timer
      description: "Timer for auto-off, set shorter than internal hood timer"
      default: 120
      selector:
        number:
          min: 10
          max: 180
          unit_of_measurement: minutes

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input speed_input
    id: numeric_change
  - platform: numeric_state
    entity_id: !input speed_input
    id: off_timer    
    above: 0
    for: 
      minutes: !input timer_off
  - platform: numeric_state
    entity_id: !input speed_input
    id: boost_timer    
    above: 3
    for: 
      minutes: !input timer_boost
action:
  - choose:
    - conditions:
      - condition: trigger
        id: numeric_change
      sequence:
      - choose:
        - conditions: # switch off at 0, send 2 extra off.
            - condition: template
              value_template: "{{ (trigger.to_state.state | int) == 0 }}"
          sequence:
            - repeat:
                count: "{{ (trigger.from_state.state | int) - (trigger.to_state.state | int) + 2 }}"
                sequence:
                  - service: rfxtrx.send
                    data:
                      event: !input command_down
                  - delay: 1
        - conditions: # faster 
            - condition: template
              value_template: "{{ (trigger.to_state.state | int) > (trigger.from_state.state | int) }}"
          sequence:
            - repeat:
                count: "{{ (trigger.to_state.state | int) - (trigger.from_state.state | int) }}"
                sequence:
                  - service: rfxtrx.send
                    data:
                      event: !input command_up
                  - delay: 1
        default: # slower
          - repeat:
              count: "{{ (trigger.from_state.state | int) - (trigger.to_state.state | int) }}"
              sequence:
                - service: rfxtrx.send
                  data:
                    event: !input command_down
                - delay: 1
    - conditions:
      - condition: trigger
        id: boost_timer
      sequence:
        - service: input_number.set_value
          alias: "Novy boost timer"
          target:
            entity_id: !input speed_input
          data:
            value: "3"
    - conditions:
      - condition: trigger
        id: off_timer
      sequence:
        - service: input_number.set_value
          alias: "Novy off timer"
          target:
            entity_id: !input speed_input
          data:
            value: "0"